[book]
title = "Notas Klosowski"
description = "Minhas notas pessoais"
authors = ["Eduardo Klosowski"]
language = "pt-BR"

[build]
create-missing = false

[preprocessor.toc]
command = "./mdbook-toc"
max-level = 8
renderer = ["html"]

[output.html]
site-url = "/notes/"
git-repository-url = "https://github.com/eduardoklosowski/notes"
git-repository-icon = "fab-github"
edit-url-template = "https://github.com/eduardoklosowski/notes/edit/main/{path}"
additional-css = ["static/toc.css"]
sidebar-header-nav = false

[output.html.fold]
enable = true
